//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviebase.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moviebase.Entities.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file extension..
        /// </summary>
        public static string AddExtensionMessage {
            get {
                return ResourceManager.GetString("AddExtensionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new detection.
        /// </summary>
        public static string AddExtensionTitle {
            get {
                return ResourceManager.GetString("AddExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently opened folder. Do you want to close it first?.
        /// </summary>
        public static string AlreadyOpenedFolderMessage {
            get {
                return ResourceManager.GetString("AlreadyOpenedFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select name..
        /// </summary>
        public static string AlternativeNameTitle {
            get {
                return ResourceManager.GetString("AlternativeNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moviebase.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to analyze..
        /// </summary>
        public static string BrowseFolderDescription {
            get {
                return ResourceManager.GetString("BrowseFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some component(s) are missing. Please install before using this application. See Settings..
        /// </summary>
        public static string ComponentMissingMessage {
            get {
                return ResourceManager.GetString("ComponentMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to export..
        /// </summary>
        public static string ExportNoDataMessage {
            get {
                return ResourceManager.GetString("ExportNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to fetch..
        /// </summary>
        public static string FetchNoDataMessage {
            get {
                return ResourceManager.GetString("FetchNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item excluded from fetch..
        /// </summary>
        public static string ItemExcludedMessage {
            get {
                return ResourceManager.GetString("ItemExcludedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string LiteralCompletedText {
            get {
                return ResourceManager.GetString("LiteralCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string LiteralDownloadingText {
            get {
                return ResourceManager.GetString("LiteralDownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move!.
        /// </summary>
        public static string LiteralMoveText {
            get {
                return ResourceManager.GetString("LiteralMoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string LiteralReadyText {
            get {
                return ResourceManager.GetString("LiteralReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string LiteralStopText {
            get {
                return ResourceManager.GetString("LiteralStopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string LiteralThreeDots {
            get {
                return ResourceManager.GetString("LiteralThreeDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageMagick is not installed. Can not use this feature..
        /// </summary>
        public static string MagickNotInstalled {
            get {
                return ResourceManager.GetString("MagickNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: {0}.
        /// </summary>
        public static string MoveMoviesCountPattern {
            get {
                return ResourceManager.GetString("MoveMoviesCountPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1}.
        /// </summary>
        public static string MovieExtraInfoPattern {
            get {
                return ResourceManager.GetString("MovieExtraInfoPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string MovieTitleInfoPattern {
            get {
                return ResourceManager.GetString("MovieTitleInfoPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Extension to Add.
        /// </summary>
        public static string NoExtensionToAddMessage {
            get {
                return ResourceManager.GetString("NoExtensionToAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found!.
        /// </summary>
        public static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opened directory is recorded..
        /// </summary>
        public static string OpenDirNoRecord {
            get {
                return ResourceManager.GetString("OpenDirNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last opened directory is missing..
        /// </summary>
        public static string OpenDirNotExist {
            get {
                return ResourceManager.GetString("OpenDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        public static string PercentagePattern {
            get {
                return ResourceManager.GetString("PercentagePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for poster downloading..
        /// </summary>
        public static string PosterNoDataMessage {
            get {
                return ResourceManager.GetString("PosterNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a poster first!.
        /// </summary>
        public static string PosterNotSelectedMessage {
            get {
                return ResourceManager.GetString("PosterNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to save..
        /// </summary>
        public static string PresistNoDataMessage {
            get {
                return ResourceManager.GetString("PresistNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to rename..
        /// </summary>
        public static string RenameNoDataMessage {
            get {
                return ResourceManager.GetString("RenameNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to analyze!.
        /// </summary>
        public static string SelectFolderMessage {
            get {
                return ResourceManager.GetString("SelectFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for thumbnail creation..
        /// </summary>
        public static string ThumbnailNoDataMessage {
            get {
                return ResourceManager.GetString("ThumbnailNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.{1}.{2} build {3}.
        /// </summary>
        public static string VersionStringPattern {
            get {
                return ResourceManager.GetString("VersionStringPattern", resourceCulture);
            }
        }
    }
}
